microsoft/mixedreality.dmx.core

DMX.Core.Api/DMX.Core.Api.csproj

Closes Task #39648471 - CONFIG: Update DMX.Core.Api Target Framework to .NET 7.0 & Disable Nullable/ImplicitUsings

CONFIG: Update DMX.Core.Api Target Framework to .NET 7.0 & Disable Nullable/ImplicitUsings

---

DMX.Core.Api.Tests.Unit/DMX.Core.Api.Tests.Unit.csproj
DMX.Core.Api.Tests.Unit/DeleteMe.cs
DMX.Core.Api.Tests.Unit/Usings.cs
DMX.Core.Api/DMX.Core.Api.csproj
DMX.Core.sln

Closes Task 39590598 INFRA: Initialize Unit Test Project

INFRA: Initialize Unit Test Project

---

.github/workflows/dotnet.yml
DMX.Core.Api.Infrastructure.Build/DMX.Core.Api.Infrastructure.Build.csproj
DMX.Core.Api.Infrastructure.Build/Program.cs
DMX.Core.sln

Closes Task #39590618 - INFRA: Implement Build Project

INFRA: Implement Build Project

---

DMX.Core.Api.Infrastructure.Build/Program.cs

CODE RUB: Using var

---

DMX.Core.Api/Brokers/ReverbApis/ReverbApiBroker.cs

CODE RUB: Removed Extra Line

---

DMX.Core.Api.Tests.Unit/Services/Foundations/LabServiceTests.Logic.RetrieveAll.cs

Closes Task #39767187: CODERUB: 'randomproperty' -> 'randomProperty'

CODERUB: 'randomproperty' -> 'randomProperty'

---

DMX.Core.Api/Controllers/LabsController.cs

Closes Task# 39767137: CODERUB: 'dependency' misspelling

CODERUB: 'dependency' misspelling

---

DMX.Core.Api/Startup.cs

CODE RUB: Refactor Broker Registration

---

DMX.Core.Api.Tests.Unit/Services/Foundations/LabServiceTests.cs
DMX.Core.Api/Controllers/LabsController.cs
DMX.Core.Api/Services/Foundations/LabService.Exceptions.cs
DMX.Core.Api/Services/Foundations/LabService.cs
DMX.Core.Api/Services/Foundations/Labs/ILabService.cs
DMX.Core.Api/Services/Foundations/Labs/LabService.Exceptions.cs
DMX.Core.Api/Services/Foundations/Labs/LabService.cs
DMX.Core.Api/Startup.cs

Here's some updates to ensure our code is very readable and easy to understand:
1. I abstracted away some of the work we needed to do to map `ExternalLab` to `Lab` components.
2. I flattened out our exception handling to ensure cognitive consistency
3. I changed `ReturningLabFunction` for the exception delegate to `ReturningLabsFunction` (variable name changed as well)
4. Move `LabService` and `ILabService` under Labs namespace/folder.

CODE RUB: Make Lab Service Pretty ❤️

---

DMX.Core.Api/Startup.cs

Closes Task #39813099: CODE RUB: Consolidate Startup services' registrations

CODE RUB: Consolidate Startup services' registrations

---

DMX.Core.Api/Services/Foundations/Labs/LabService.cs
DMX.Core.Api/Startup.cs

CODE RUB: Code Clean Up

---

README.md

DOCUMENTATION: Add Build Status Badge

---

DMX.Core.Api.Tests.Unit/Services/Foundations/LabServiceTests.cs
DMX.Core.Api/DMX.Core.Api.csproj

Closes Task #39906368 - CODE RUB: Update 'Xeption' NuGet Package and Use SameExceptionAs

CODE RUB: Update 'Xeption' NuGet Package and Use SameExceptionAs

---

DMX.Core.Api.Tests.Unit/Services/Foundations/Labs/LabServiceTests.Exceptions.RetrieveAll.cs
DMX.Core.Api.Tests.Unit/Services/Foundations/Labs/LabServiceTests.Logic.RetrieveAll.cs
DMX.Core.Api/Services/Foundations/Labs/ILabService.cs
DMX.Core.Api/Services/Foundations/Labs/LabService.cs

Closes Task #40261023 - CODE RUB: Change RetrieveAllLabs to RetrieveAllLabsWithDevices

CODE RUB: Change `RetrieveAllLabs` to `RetrieveAllLabsWithDevices`

---

DMX.Core.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.WebApps.cs
DMX.Core.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.cs
DMX.Core.Api.Infrastructure.Provision/DMX.Core.Api.Infrastructure.Provision.csproj

This effort will add external lab configurations during provisioning using github secrets.

CONFIG: Add External Lab Configurations

---

.github/workflows/provision.yml
DMX.Core.Api.Infrastructure.Build/Services/ScriptGenerations/ScriptGenerationService.cs
DMX.Core.Api.Infrastructure.Provision/Brokers/Configurations/ConfigurationBroker.cs
DMX.Core.Api.Infrastructure.Provision/DMX.Core.Api.Infrastructure.Provision.csproj
DMX.Core.Api.Infrastructure.Provision/appSettings.json
DMX.Core.Api.Tests.Unit/Services/Orchestrations/LabOrchestrationServiceTests.Logic.RetrieveAll.cs
DMX.Core.Api.Tests.Unit/Services/Orchestrations/LabOrchestrationServiceTests.cs
DMX.Core.Api/Controllers/LabsController.cs

Also ran code cleanup on the whole project.

MAJOR FIX: Fix Target Branch

---

.github/workflows/provision.yml
DMX.Core.Api.Infrastructure.Build/Services/ScriptGenerations/ScriptGenerationService.cs
DMX.Core.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.cs

Removes subscriptionId as well

MAJOR FIX: Update TenentId to TenantId

---

DMX.Core.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.WebApps.cs
DMX.Core.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.cs
DMX.Core.Api.Tests.Unit/Services/Orchestrations/LabOrchestrationServiceTests.Exceptions.Add.cs
DMX.Core.Api.Tests.Unit/Services/Orchestrations/LabOrchestrationServiceTests.Logic.Add.cs

PROVISION: Set 'Production' Environment Variable on Provisioning of API

---

DMX.Core.Api/Controllers/LabsController.cs

CONFIG: Disarm Authentication for Acceptance Tests

---

DMX.Core.Api/Controllers/LabCommandsController.cs

CONTROLLERS: Post LabCommands

---

DMX.Core.Api/Controllers/LabCommandsController.cs

CONTROLLERS: Get LabCommand by Id

---

DMX.Core.Api/Controllers/LabCommandsController.cs

**Post New Lab:**
**Modify New Lab:**
**Failed Modify New Lab (Input CreatedDate != Stored CreatedDate):**
**Failed Modify New Lab (UpdatedDate is not recent):**

CONTROLLERS: Put Lab Command
